version: "3.7"
services:
  soda-sql-postgres:
    image: postgres:9.6.17-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=soda_test
      - POSTGRES_DB=soda_test
      - POSTGRES_HOST_AUTH_METHOD=trust
